# inspired by https://github.com/BretFisher/node-docker-good-defaults

version: '3.7'

services:
  baas:
    image: baas_admin:prod
    deploy:
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.docker.network=proxy
        - traefik.http.routers.baas.rule=Host(`admin.localhost`)
        - traefik.http.services.baas.loadbalancer.server.port=3000
      update_config:
        failure_action: rollback
        order: start-first
    environment:
      - DB_USERNAME=baas
      - DB_PASSWORD=aLongAndComplicatedSecret
      - DB_HOSTNAME=postgres
      - DB_DBNAME=baas_admin
      - REDIS_HOSTNAME=redis
      - SESSION_SECRET=aSuperSecureString
    volumes:
      - frontends:/opt/node_app/app/uploads
      - /var/run/docker.sock:/var/run/docker.sock
    # depends_on:
    #   - postgres
    #   - redis
    networks:
      - admin-backend
      - proxy

volumes:
  frontends:
    name: frontends

networks:
  admin-backend:
    external: true
  proxy:
    external: true
